version: "3"
services:
    db-prod:
      container_name: db-prod
      image: postgres:9.6-buster
      networks:
        - prod_net_back
      ports:
        - 9990:5432
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=tasks
        - POSTGRES_USER=tasks
          #volumes:
          #    - prod_postgresql:/var/lib/postgresql
          #    - prod_postgresql_data:/var/lib/postgresql/data
              
    # backend:
    #     container_name: backend-prod
    #     # image: back_prod:build_${BUILD_NUMBER}
    #     image: back_prod:build_
    #     build:
    #         context: .
    #         args:
    #             - WAR_FILE=target/tasks-backend.war
    #             - CONTEXT=tasks-backend
    #     networks:
    #         - prod_net_back
    #         - prod_net_front
    #     ports:
    #       - 9998:8080
    #     environment:
    #         - DATABASE_HOST=db-prod
    #         - DATABASE_PORT=5432
    #         - DATABASE_USER=tasks
    #         - DATABASE_PASSWD=password
    #         #- DATABASE_UPDATE=none
    #     depends_on:
    #         - db-prod

    # frontend:
    #     container_name: frontend-prod
    #     # image: front_prod:build_${BUILD_NUMBER}
    #     image: front_prod:build_
    #     build:
    #         context: .
    #         args:
    #             - WAR_FILE=tasks-front/target/tasks.war
    #             - CONTEXT=tasks
    #     networks:
    #         - prod_net_front
    #     ports:
    #         - 9999:8080
    #     links: 
    #         - backend
    #     environment:
    #         - BACKEND_HOST=backend
    #         - BACKEND_PORT=8080
    #       # - APP_VERSION=build_${BUILD_NUMBER}
    #         - APP_VERSION=build_
    #     depends_on:    
    #         - backend 
              
networks:
  prod_net_front:
  prod_net_back:

          #volumes:
        #  prod_postgresql:
          #  prod_postgresql_data:
